config/routes.rb
SampleApp::Application.routes.draw do
  root 'static_pages#home'

  match '/signup', to: 'users#new', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'

  match 'signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'delete'

  resources :users do
    member do
      get :followers, :following
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/partials/_footer.html.erb
<footer id="footer">
  <div class="container">
      <small>
        <a href="http://railstutorial.org/">Initial Project</a>
        |
        <a href="http://kakkoyun.me/">Further information of current version</a>
        by Kemal Akkoyun.
      </small>
      <nav>
        <ul>
          <li><%= link_to "About",   about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><a href="http://news.railstutorial.org/">News</a></li>
        </ul>
      </nav>
  </div>
</footer>

app/views/layouts/partials/_header.html.erb
<header id="header" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right pull-right">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Help', help_path %></li>
          <% if signed_in? %>
          <li><%= link_to "Users", users_path %></li>

          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>

            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign-out", signout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to 'Sign-in', signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/partials/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->